PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#>
PREFIX aq: <http://rdfdata.eionet.europa.eu/airquality/ontology/>
PREFIX aqr: <http://reference.eionet.europa.eu/aq/ontology/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX aqdd: <http://dd.eionet.europa.eu/property/>
PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#> 

SELECT DISTINCT

md5(concat(?Country, xsd:string(?ReportingYear),xsd:string(?AttainmentYear),?Namespace ,?ScenariosId ,?VersionId ,?CodeOfScenario,?BaselineDescription, ?BaselineComment,  xsd:string(?BaselineEmissions) ,xsd:string(?BaselineExpectedConcentration), ?ProjectionDescription, ?ProjectionComment,  xsd:string(?ProjectionEmissions), xsd:string(?ProjectionExpectedConcentration) ,?SourceApportionmentId ,?PlanId ,?envelope
)
)  as ?_id


?XMLURI 
#bif:concat(xsd:string(YEAR(?endOfPeriod)), '-', ?ScenariosId ) as ?_id
?Country as ?CountryOrTerritory 
year(xsd:date(?endOfPeriod)) AS ?ReportingYear 
?AttainmentYear 
?Namespace 
?ScenariosId 
?VersionId 
?CodeOfScenario 
?BaselineDescription 
?BaselineComment 
?BaselineEmissions 
?BaselineExpectedConcentration 
?BaselineExpectedNrExceedances
?ProjectionDescription 
?ProjectionComment 
?ProjectionEmissions 
?ProjectionExpectedConcentration 
?ProjectionExpectedNrExceedances
replace(replace(replace(str(?SourceApportionmentId),"http://reference.eionet.europa.eu/aq/",""),?Namespace ,""),"/","") as ?SourceApportionmentId
replace(replace(replace(str(?PlanId),"http://reference.eionet.europa.eu/aq/",""),?Namespace ,""),"/","") as ?PlanId 
?envelope

 WHERE {{
  GRAPH ?source {
    ?XMLURI a aq:AQD_EvaluationScenario .
    ?XMLURI aq:inspireId ?inspireURI .
  }
  ?source dcterms:isPartOf ?envelope .
  ?envelope rod:released ?released .
  ?envelope rod:locality ?locality .
  ?envelope rod:obligation ?obliURI .
  ?envelope rod:endOfPeriod ?endOfPeriod .

  ?inspireURI aq:namespace ?Namespace .
  ?inspireURI aq:localId ?ScenariosId .

   OPTIONAL {?XMLURI aq:versionId ?VersionId} .
   OPTIONAL {?XMLURI aq:attainmentYear ?attyearURI . 
             ?XMLURI aq:codeOfScenario ?CodeOfScenario . 
             ?XMLURI aq:sourceApportionment ?SourceApportionmentId . 
             ?XMLURI aq:usedInPlan ?PlanId .   
             ?XMLURI aq:baselineScenario ?baselineURI . 
             ?XMLURI aq:projectionScenario ?projectionURI . 
             ?XMLURI aq:publication ?publicationURI .
             ?attyearURI rdfs:label ?AttainmentYear .
   }  

   OPTIONAL {?baselineURI aq:description ?BaselineDescription .
             ?baselineURI aq:comment ?BaselineComment .
             ?baselineURI aq:totalEmissions ?BaselineEmissions .
             ?baselineURI aq:expectedConcentration ?BaselineExpectedConcentration .
             ?baselineURI aq:expectedExceedances ?BaselineExpectedNrExceedances
   }
   ##OPTIONAL {?baselineURI aq:measuresApplied ?BaselineMeasuresApplied} .

   OPTIONAL {?projectionURI aq:description ?ProjectionDescription .
             ?projectionURI aq:comment ?ProjectionComment .
             ?projectionURI aq:totalEmissions ?ProjectionEmissions .
             ?projectionURI aq:expectedConcentration ?ProjectionExpectedConcentration .
             ?projectionURI aq:expectedExceedances ?ProjectionExpectedNrExceedances
   }
   ##OPTIONAL {?projectionURI aq:measuresApplied ?ProjectionMeasuresApplied} .

   ?locality rod:localityName ?Country .
   ?obliURI rdfs:label ?Obligation .

  #FILTER (?envelope = <http://cdr.eionet.europa.eu/dk/eu/aqd/j/envvngbuq>)
  FILTER (?envelope = <<envelope>>)
   
}}
