PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#>
PREFIX aq: <http://rdfdata.eionet.europa.eu/airquality/ontology/>
PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>
PREFIX obligations: <http://rod.eionet.europa.eu/obligations/>

SELECT DISTINCT

md5(concat(?Country, ?ZoneCode, ?LocalId, ?Namespace, ?GeographicalName, xsd:string(?startOfPeriod), xsd:string(?BeginTime), ?AQDZoneType, xsd:string(?ResidentPopulation), xsd:string(?ResidentPopulationYear), xsd:string(?Area), ?TimeExtensionExemption, ?Pollutant, ?ProtectionTarget, ?CompetentAuthority, ?ContactName, ?Telephone, ?Address, ?Email, ?Website, ?envelope))  as ?_id

#?XMLURI
#?source     
#?envelope     
#?obliURI     
?Country as ?CountryOrTerritory 
?ZoneCode
?LocalId as ?ZoneId
?Namespace
YEAR(xsd:date(?startOfPeriod)) AS ?ReportingYear 
?GeographicalName
?BeginTime
?EndTime
?AQDZoneType
?ResidentPopulation
?ResidentPopulationYear
?Area
?TimeExtensionExemption
?Pollutant
?ProtectionTarget
?CompetentAuthority
#?ContactName
?Telephone
?Address
#?Email
?Website
?envelope

WHERE {{

  #test DE
  #values ?envelope { <http://cdr.eionet.europa.eu/de/eu/aqd/b/colxotqa/envxthsxg> }
  #values ?released { '2019-07-24T13:06:05Z' }
  #values ?startOfPeriod { '2018-01-01' }
  #values ?Country { 'Germany' }
  #GRAPH <http://cdr.eionet.europa.eu/de/eu/aqd/b/colxotqa/envxthsxg/DE_B_Zones_2018.xml> {

  #test LV
  #values ?envelope { <http://cdr.eionet.europa.eu/lv/eu/aqd/b/envxrmrsg> }
  #values ?released { '2019-06-26T07:02:07Z' }
  #values ?startOfPeriod { '2018-01-01' }
  #values ?Country { 'Latvia' }
  #GRAPH <http://cdr.eionet.europa.eu/lv/eu/aqd/b/envxrmrsg/REP_LV_LEGMC_20190626_B_v0.xml> {

  values ?envelope { <<envelope>> }
  values ?released { '<released>' }
  values ?startOfPeriod { '<startOfPeriod>' }
  values ?Country { '<Country>' }
  GRAPH <<source>> {
    ?XMLURI a aq:AQD_Zone .
    ?XMLURI aq:inspireId ?inspireURI .
    ?XMLURI aq:name ?GeographicalName .
    ?XMLURI aq:zoneCode ?ZoneCode .
    ?XMLURI aq:aqdZoneType ?aqdzonetype .
    ?XMLURI aq:residentPopulation ?ResidentPopulation .
    ?XMLURI aq:area ?Area .
    ?XMLURI aq:designationPeriod ?timeURI .
    ?XMLURI aq:pollutants ?polltargetURI .
    ?inspireURI aq:localId ?LocalId .
    ?inspireURI aq:namespace ?Namespace .

  }
  ?polltargetURI aq:protectionTarget ?Protection .
  ?polltargetURI aq:pollutantCode ?pollURI .
  ?pollURI skos:notation ?Pollutant .
  ?Protection rdfs:label ?ProtectionTarget .
  ?aqdzonetype rdfs:label ?AQDZoneType .
  ?timeURI aq:beginPosition ?BeginTime .


#  OPTIONAL{?timeURI aq:endPosition ?EndTime} .
   OPTIONAL{?XMLURI aq:residentPopulationYear ?popYearURI .
            ?popYearURI rdfs:label ?ResidentPopulationYear .
   }

  OPTIONAL{?XMLURI aq:timeExtensionExemption ?timeextensionexemptionURI .
           ?timeextensionexemptionURI rdfs:label ?TimeExtensionExemption .
           ?XMLURI aq:competentAuthority ?CompetentAuthorityURI .
           ?CompetentAuthorityURI rdfs:label ?CompetentAuthority .
           ?CompetentAuthorityURI aq:individualName ?ContactName .
           ?CompetentAuthorityURI aq:contact ?ContactURI .
           ?ContactURI aq:address ?AddressURI  .
           ?AddressURI aq:adminUnit ?Address .
#  OPTIONAL{?ContactURI aq:electronicMailAddress ?Email} .
           ?ContactURI aq:telephoneVoice ?Telephone .
           ?ContactURI aq:website ?Website
   } 
   }
}
