PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#>
PREFIX aq: <http://rdfdata.eionet.europa.eu/airquality/ontology/>
PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>
PREFIX obligations: <http://rod.eionet.europa.eu/obligations/>

SELECT DISTINCT

md5(concat(?Country, ?ZoneCode, ?LocalId, ?Namespace, ?GeographicalName, xsd:string(?startOfPeriod), xsd:string(?BeginTime), ?AQDZoneType, xsd:string(?ResidentPopulation), xsd:string(?ResidentPopulationYear), xsd:string(?Area), ?TimeExtensionExemption, ?Pollutant, ?ProtectionTarget, ?CompetentAuthority, ?ContactName, ?Telephone, ?Address, ?Email, ?Website, ?envelope))  as ?_id

#?XMLURI
#?source     
#?envelope     
#?obliURI     
?Country as ?CountryOrTerritory 
?ZoneCode
?LocalId as ?ZoneId
?Namespace
YEAR(xsd:date(?startOfPeriod)) AS ?ReportingYear 
?GeographicalName
?BeginTime
?EndTime
?AQDZoneType
?ResidentPopulation
?ResidentPopulationYear
?Area
?TimeExtensionExemption
?Pollutant
?ProtectionTarget
?CompetentAuthority
#?ContactName
?Telephone
?Address
#?Email
?Website
?envelope

WHERE {{
  GRAPH ?source {
    ?XMLURI a aq:AQD_Zone .
    ?XMLURI aq:inspireId ?inspireURI .
    ?XMLURI aq:name ?GeographicalName .
    ?XMLURI aq:zoneCode ?ZoneCode .
    ?XMLURI aq:aqdZoneType ?aqdzonetype .
    ?XMLURI aq:residentPopulation ?ResidentPopulation .
    ?XMLURI aq:area ?Area .
    ?XMLURI aq:designationPeriod ?timeURI .
    ?XMLURI aq:pollutants ?polltargetURI .
  }
  ?source dcterms:isPartOf ?envelope .
  ?envelope rod:released ?released .
  ?envelope rod:locality ?locality .
  ?envelope rod:obligation ?obliURI .
  ?envelope rod:startOfPeriod ?startOfPeriod .

  ?inspireURI aq:localId ?LocalId .
  ?inspireURI aq:namespace ?Namespace .
  ?polltargetURI aq:protectionTarget ?Protection .
  ?polltargetURI aq:pollutantCode ?pollURI .
  ?pollURI skos:notation ?Pollutant .
  ?Protection rdfs:label ?ProtectionTarget .
  ?aqdzonetype rdfs:label ?AQDZoneType .
  ?timeURI aq:beginPosition ?BeginTime .

#  OPTIONAL{?timeURI aq:endPosition ?EndTime} .
   OPTIONAL{?XMLURI aq:residentPopulationYear ?popYearURI .
            ?popYearURI rdfs:label ?ResidentPopulationYear .
   } .

  OPTIONAL{?XMLURI aq:timeExtensionExemption ?timeextensionexemptionURI .
           ?timeextensionexemptionURI rdfs:label ?TimeExtensionExemption .
           ?XMLURI aq:competentAuthority ?CompetentAuthorityURI .
           ?CompetentAuthorityURI rdfs:label ?CompetentAuthority .
           ?CompetentAuthorityURI aq:individualName ?ContactName .
           ?CompetentAuthorityURI aq:contact ?ContactURI .
           ?ContactURI aq:address ?AddressURI  .
           ?AddressURI aq:adminUnit ?Address .
#  OPTIONAL{?ContactURI aq:electronicMailAddress ?Email} .
           ?ContactURI aq:telephoneVoice ?Telephone .
           ?ContactURI aq:website ?Website} .

  ?locality rod:localityName ?Country .
  ?obliURI rdfs:label ?Obligation .

  FILTER (?envelope = <<envelope>>)
}}
