PREFIX daviz: <http://www.eea.europa.eu/portal_types/DavizVisualization#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT distinct (?visualization as ?_id) ?visualization ?description ?title ?creator ?created (year(?created) as ?year)
WHERE {
  ?visualization a daviz:DavizVisualization
     optional{?visualization dct:description ?description}
     optional{?visualization dct:title ?title}
     optional{?visualization dct:creator ?creator}
     optional{?visualization dct:created ?created}
}