PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#>
PREFIX aq: <http://rdfdata.eionet.europa.eu/airquality/ontology/>
PREFIX aqr: <http://reference.eionet.europa.eu/aq/ontology/>
PREFIX dd: <http://dd.eionet.europa.eu/property/>

SELECT DISTINCT 

?Pollutant_URI 
?offset
WHERE {
  ?statsURI aqr:pollutant ?Pollutant_URI .
  {{
    SELECT DISTINCT ?offset WHERE
    {{
      ?bookmark a cr:SparqlBookmark
      { SELECT 0 AS ?offset {} }
        UNION
      { SELECT 80000 AS ?offset {} }
        UNION
      {  SELECT 160000 AS ?offset {} }
        UNION
      {  SELECT 240000 AS ?offset {} }
    }}
  }}
}