PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#>
PREFIX aq: <http://rdfdata.eionet.europa.eu/airquality/ontology/>
PREFIX aqr: <http://reference.eionet.europa.eu/aq/ontology/>
PREFIX dd: <http://dd.eionet.europa.eu/property/>

SELECT DISTINCT 

?AggregationType_URI
xsd:integer(year(xsd:date(?BeginPosition))) as ?ReportingYear

WHERE {

  ?statsURI a aqr:ValidatedExceedence .
  ?statsURI aqr:aggregationType ?AggregationType_URI .
  ?statsURI aqr:beginPosition ?BeginPosition
}
