PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#>
PREFIX aq: <http://rdfdata.eionet.europa.eu/airquality/ontology/>
PREFIX aqr: <http://reference.eionet.europa.eu/aq/ontology/>
PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>
PREFIX obligations: <http://rod.eionet.europa.eu/obligations/>
PREFIX aqdd: <http://dd.eionet.europa.eu/property/>

SELECT DISTINCT

md5(concat(?Country, xsd:string(?endOfPeriod),?PlanCode ,?Namespace ,?PlanId ,?VersionId ,?Name, xsd:string(?FirstExceedanceYear) ,xsd:string(?AdoptionDate) ,?Status ,xsd:string(?TimeTable) ,?ReferenceAQPlan ,?ReferenceImplementation,?Pollutant ,?ProtectionTarget ,?PublicationTitle ,xsd:string(?PublicationDate) ,?PublicationAuthor,?PublicationDescription ,?Publisher ,?PublicationWeblink ,?Organisation ,xsd:string(?Phone) ,?Website ,?Address ,?Comment ,?AttainmentId ,?envelope))  as ?_id


#?XMLURI
?Country as ?CountryOrTerritory 
year(xsd:date(?endOfPeriod)) AS ?ReportingYear 
?PlanCode 
?Namespace 
?PlanId 
?VersionId 
?Name 
?FirstExceedanceYear 
?AdoptionDate 
?Status 
?TimeTable 
?ReferenceAQPlan 
?ReferenceImplementation 
?Pollutant 
?ProtectionTarget 
?PublicationTitle 
?PublicationDate 
?PublicationAuthor 
?PublicationDescription 
?Publisher
?PublicationWeblink 
?Organisation 
?Phone 
?Website 
?Address 
sql:GROUP_CONCAT(?Comment,' ') AS ?Comment
#replace(replace(replace(str(?excURI),"http://reference.eionet.europa.eu/aq/",""),?Namespace ,""),"/","") as ?AttainmentId 
?envelope

WHERE {{
  GRAPH ?source {
    ?XMLURI a aq:AQD_Plan .
    ?XMLURI aq:inspireId ?inspireURI .
    ?XMLURI aq:code ?PlanCode .
    ?XMLURI aq:name ?Name .
    ?XMLURI aq:competentAuthority ?compAuthorityURI .
    ?XMLURI aq:firstExceedanceYear ?firstexcURI .
    ?XMLURI aq:adoptionDate ?adoptionURI .
    ?XMLURI aq:timeTable ?TimeTable .
    ?XMLURI aq:referenceAQPlan ?ReferenceAQPlan .
    ?XMLURI aq:referenceImplementation ?ReferenceImplementation .
    ?XMLURI aq:pollutants ?pollURI .
    ?XMLURI aq:publication ?publURI .
    ?XMLURI aq:status ?StatusURI .
  }
  ?source dcterms:isPartOf ?envelope .
  ?envelope rod:released ?released .
  ?envelope rod:locality ?locality .
  ?envelope rod:obligation ?obliURI .
  ?envelope rod:endOfPeriod ?endOfPeriod .

  OPTIONAL{?XMLURI aq:comment ?Comment} .
  OPTIONAL{?XMLURI aq:exceedanceSituation ?excURI} .
  OPTIONAL{?excURI aqr:inspireId ?AttainmentId} .
  OPTIONAL{?excURI dcterms:source ?source} .
  OPTIONAL{?excenvelope rod:hasFile ?source} .

  ?inspireURI aq:namespace ?Namespace .
  ?inspireURI aq:localId ?PlanId .
  OPTIONAL{?inspireURI aq:versionId ?VersionId} .

  ?compAuthorityURI aq:organisationName ?Organisation .
  ?compAuthorityURI aq:contact ?contactURI .

  ?contactURI aq:telephoneVoice ?Phone .
  ?contactURI aq:website ?Website .
  ?contactURI aq:address ?addressURI .

  OPTIONAL{?addressURI aq:locatorDesignator ?Address} .
  ?firstexcURI aq:timePosition ?FirstExceedanceYear .
  ?adoptionURI aq:timePosition ?AdoptionDate .

  ?pollURI aq:pollutantCode ?pollcodeURI .
  ?pollURI aq:protectionTarget ?proTargetURI .

  ?pollcodeURI skos:notation ?Pollutant .
  ?proTargetURI rdfs:label ?ProtectionTarget .

  ?publURI aq:title ?PublicationTitle .
  ?publURI aq:description ?PublicationDescription .
  ?publURI aq:publisher ?Publisher .
  ?publURI aq:webLink ?PublicationWeblink .
  ?publURI aq:publicationDate ?DateURI .

  OPTIONAL{?publURI aq:author ?PublicationAuthor}.

  ?DateURI aq:timePosition ?PublicationDate . 
  ?StatusURI rdfs:label ?Status .

  ?locality rod:localityName ?Country .
  ?obliURI rdfs:label ?Obligation .
 
  #FILTER (?envelope = <http://cdr.eionet.europa.eu/cz/eu/aqd/h/envwfeulw>)
#  FILTER (?envelope = <<envelope>>)
}}