

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>
PREFIX obligation: <http://rod.eionet.europa.eu/obligations/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX contreg: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#>

SELECT DISTINCT
?envelope
?source
?Country
?Obligation
?released
?startOfPeriod
WHERE {{
  SELECT DISTINCT
    ?Country
    YEAR(xsd:date(?startOfPeriod)) as ?reportingYear
    max(?released) as ?released
  WHERE {
    ?envelope rod:released ?released .
    ?envelope rod:startOfPeriod ?startOfPeriod .
    ?envelope rod:obligation obligation:694 .
    ?envelope rod:locality ?locality .
    ?locality rod:localityName ?Country .
  } GROUP BY ?Country YEAR(xsd:date(?startOfPeriod))
}
?envelope rod:released ?released .
?envelope rdf:type rod:Delivery .
?source dcterms:isPartOf ?envelope .
?source contreg:xmlSchema ?xmlSchema .
?envelope rod:locality ?locality .
?locality rod:localityName ?Country .
?envelope rod:obligation ?obliURI .
?obliURI rdfs:label ?Obligation .
?envelope rod:released ?released .
?envelope rod:locality ?locality .
?envelope rod:startOfPeriod ?startOfPeriod .
}
ORDER BY ?startOfPeriod ?Country
