

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>
PREFIX obligation: <http://rod.eionet.europa.eu/obligations/>
PREFIX aq: <http://rdfdata.eionet.europa.eu/airquality/ontology/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT
?envelope
WHERE {{
  SELECT DISTINCT
    ?Country
    YEAR(xsd:date(?endOfPeriod)) as ?reportingYear
    max(?released) as ?released
    ?SourceApportionmentId
    ?source
  WHERE {
    ?envelope rod:released ?released .
    ?envelope rod:endOfPeriod ?endOfPeriod .
    ?envelope rod:obligation ?obligation .
    ?envelope rod:hasFile ?source .
    ?envelope rod:locality ?locality .
    FILTER (?obligation = obligation:681) 
    ?locality rod:localityName ?Country .

    { 
      SELECT
        ?XMLURI
        ?SourceApportionmentId
        ?g as ?source
      WHERE {
         GRAPH ?g { ?XMLURI a aq:AQD_SourceApportionment . }
         ?XMLURI aq:inspireId ?inspireURI .
         ?inspireURI aq:localId ?SourceApportionmentId .
      }
    }
  } GROUP BY ?Country YEAR(xsd:date(?endOfPeriod)) ?SourceApportionmentId ?source
}
?envelope rod:released ?released .
?envelope rdf:type rod:Delivery .
}
ORDER BY ?endOfPeriod ?Country
