version: "2"

services:
  apache:
    image: eeacms/apache:latest
    ports:
    - "80:80"
    depends_on:
    - plone
    environment:
      APACHE_CONFIG: |-
        <VirtualHost *:80>

            ServerAdmin contact@localhost
            ServerName climate-local.com
            ErrorLog /var/log/apache.log

            RewriteEngine On
            LogLevel debug rewrite:trace8

            RewriteRule ^/data\-and\-downloads/(.*) http://app:3000/$$1 [P]
            RewriteRule ^/observatory/catalogue/(.*) http://health_catalog_app:3000/$$1 [P]
            RewriteRule ^/observatory/contributors/(.*) http://health_contributors_app:3000/$$1 [P]

            # RewriteRule /esbootstrap_resources/(.*) http://health-catalog-app:3000/esbootstrap_resources/$$1 [P]

            RewriteRule ^/(.*) http://plone:8080/VirtualHostBase/http/localhost:80/cca/VirtualHostRoot/$$1 [P,L]

            # RewriteRule ^/observatory/catalogue/(facetview.*) http://health_catalog_app:3000/$$1 [P]
            # RewriteRule ^/observatory/(javascripts.*) http://health_catalog_app:3000/javascripts/$$1 [P]
            # RewriteRule ^/observatory(/css/.*) http://health_catalog_app:3000/css/$$1 [P]

            # CCA default search
            # RewriteRule ^/(.*facetview.*) http://app:3000/$$1 [P]
            # RewriteRule ^(/javascripts.*) http://app:3000/$$1 [P]
            # RewriteRule ^(/css/.*) http://app:3000/$$1 [P]
            #
            # RewriteRule ^/(.*esbootstrap\_resources.*) http://app:3000/$$1 [P,L]
            #
            # RewriteRule ^/.*(tools\/api.*) http://app:3000/$$1 [P,L]
            # RewriteRule ^/.*(tools\/download.*) http://app:3000/$$1 [P,L]
            #
            # RewriteRule ^/(.*data\-and\-downloads.*) http://app:3000/$$1 [P,L]
            # RewriteRule ^/(knowledge\/tools.*) http://plone:8080/VirtualHostBase/http/localhost:80/cca/VirtualHostRoot/$$1 [P,L]

            # RewriteRule ^/observatory\/contributors(.*) http://health_contributors_app:3000/$$1 [P,L]

        </VirtualHost>

  plone:
    image: eeacms/eea.docker.plone-climateadapt:v7.33
    environment:
      TZ: Europe/Copenhagen
      ZOPE_MODE: standalone
    volumes:
      - ./plone-data/:/data
      - ./src/:/plone/instance/src/
    ports:
    - 8080:8080/tcp
    entrypoint: sh -c "tail -f /dev/null"
    # Run with docker-compose exec plone bash, then: bin/standalone fg

  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label: cca=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - "-m"
    - "2048"

  app:
    image: eeacms/esbootstrap:v3.0.28
#    build: ../
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      VERSION_INFO: eeacms/esbootstrap
      elastic_host: esmaster
      elastic_port: '9200'
      elastic_index: 'climate'
      AUTO_INDEXING: 'false'
      APP_CONFIG_DIRNAME: cca
      elastic_rwuser: 'rw'
      elastic_rwpass: 'rwtest'
      elastic_rouser: 'ro'
      elastic_ropass: 'rotest'
      elastic_appalias: 'latest'
      _API_token: 'default'
      _sourceconf_bulksize: 10
    entrypoint:
      - /node_modules/.bin/nodemon
      - --watch
      - code/
      - --watch
      - /node_modules/eea-searchserver
      - /code/app.js
#      - --inspect-brk=0.0.0.0
    command:
      - runserver
#    entrypoint: /bin/sh -c 'tail -f /dev/null'
    volumes:
        - ./cca/:/code/config/cca
#        - ./cca/eea.searchserver.js/lib/:/node_modules/eea-searchserver/lib/:z
#        - ./start_dev.sh:/start_dev.sh
#        - ./eea.docker.esbootstrap/app/:/code/:z
#        - ./eea.searchserver.js/index.js:/node_modules/eea-searchserver/index.js:z

  health_catalog_app:
    image: eeacms/esbootstrap:v3.0.28
#    build: ../
    ports:
      - '3001:3000'
      - '9232:9229'
    environment:
      VERSION_INFO: eeacms/esbootstrap
      elastic_host: esmaster
      elastic_port: '9200'
      elastic_index: 'climate'
      AUTO_INDEXING: 'false'
      APP_CONFIG_DIRNAME: health_catalog
      elastic_rwuser: 'rw'
      elastic_rwpass: 'rwtest'
      elastic_rouser: 'ro'
      elastic_ropass: 'rotest'
      elastic_appalias: 'latest'
      _API_token: 'default'
      _sourceconf_bulksize: 10
    entrypoint:
      - /node_modules/.bin/nodemon
      - --watch
      - code/
      - --watch
      - /node_modules/eea-searchserver
      - /code/app.js
#      - --inspect-brk=0.0.0.0
    command:
      - runserver
#    entrypoint: /bin/sh -c 'tail -f /dev/null'
    volumes:
        - ./health_catalog:/code/config/health_catalog
        # - ./eea.searchserver.js/lib/:/node_modules/eea-searchserver/lib/:z


#        - ./start_dev.sh:/start_dev.sh
#        - ./eea.docker.esbootstrap/app/:/code/:z
#        - ./eea.searchserver.js/index.js:/node_modules/eea-searchserver/index.js:z

  health_contributors_app:
    image: eeacms/esbootstrap:v3.0.28
#    build: ../
#    image: eeacms/esbootstrap:v2.0.18
    ports:
      - '3002:3000'
      - '9231:9229'
    environment:
      VERSION_INFO: eeacms/esbootstrap
      elastic_host: esmaster
      elastic_port: '9200'
      elastic_index: 'climate'
      AUTO_INDEXING: 'false'
      APP_CONFIG_DIRNAME: health_contributors
      elastic_rwuser: 'rw'
      elastic_rwpass: 'rwtest'
      elastic_rouser: 'ro'
      elastic_ropass: 'rotest'
      elastic_appalias: 'latest'
      _API_token: 'default'
      _sourceconf_bulksize: 10
    entrypoint:
      - /node_modules/.bin/nodemon
      - --watch
      - code/
      - --watch
      - /node_modules/eea-searchserver
      - /code/app.js
#      - --inspect-brk=0.0.0.0
    command:
      - runserver
#    entrypoint: /bin/sh -c 'tail -f /dev/null'
    volumes:
        - ./health_contributors:/code/config/health_contributors
#        - ./eea.searchserver.js/lib/:/node_modules/eea-searchserver/lib/:z
#        - ./start_dev.sh:/start_dev.sh
#        - ./eea.docker.esbootstrap/app/:/code/:z
#        - ./eea.searchserver.js/index.js:/node_modules/eea-searchserver/index.js:z

  esmaster:
    image: eeacms/elastic:6.8-1.1
    ports:
      - "9200:9200"
    environment:
        - "cluster.name=es6_test"
        - "cluster.routing.allocation.disk.threshold_enabled=false"
        - "node.name=es6"
        - "bootstrap.memory_lock=true"
        - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
        - "node.master=true"
        - "node.data=true"
        - "http.enabled=true"
        - "RW_USER=rw"
        - "RO_USER=ro"
        - "RW_PASSWORD=rwtest"
        - "RO_PASSWORD=rotest"
        - "KIBANA_USER=user_kibana"
        - "KIBANA_PASSWORD=kibana_pass"
        - "KEY_PASSWORD=Abc123;"
        - "KEYSTORE_PASSWORD=Def123;"
        - "ENABLE_READONLY_REST=false"
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
    mem_limit: 10737418240
    mem_swappiness: 0
    cap_add:
        - IPC_LOCK
    depends_on:
        - es-sysctl
    volumes:
      - ./es-data:/usr/share/elasticsearch/data

  # this service is used to make esmaster happy. We care about its happiness
  es-sysctl:
      network_mode: none
      image: rawmind/alpine-sysctl:0.1
      privileged: true
      environment:
          - "SYSCTL_KEY=vm.max_map_count"
          - "SYSCTL_VALUE=262144"

# volumes:
#   cca-async-data:
#   cca-downloads:
#   plone-data:
