esmaster:
    image: eeacms/elastic:1.7.5-1.6
#    build: ./eea.docker.elastic/
    restart: always
    command: # No data, no http, no river, can be master
        - elasticsearch
        - -Des.cluster.name="es_zotya_test"
        - -Des.node.name=Master
        - -Des.node.data=false
        - -Des.http.enabled=false
        - -Des.node.master=true
        - -Des.node.river=_none_
    volumes_from:
        - datam

datam:
    image: busybox
    tty: true
    command:
        - cat
    volumes:
        - /usr/share/elasticsearch/data
    stdin_open: true

esclient:
    image: eeacms/elastic:1.7.5-1.6
#    build: ./eea.docker.elastic/
    restart: always
    command: # No data, http, no river, can't be master
        - elasticsearch
        - -Des.cluster.name="es_zotya_test"
        - -Des.node.name=Client
        - -Des.node.data=false
        - -Des.http.enabled=true
        - -Des.node.master=false
        - -Des.node.river=_none_
    ports:
        - 9200:9200

esworker1:
    image: eeacms/elastic:1.7.5-1.6
#    build: eea.docker.elastic
    restart: always
    command: # Data, no http, river, can't be master
        - elasticsearch
        - -Des.cluster.name="es_zotya_test"
        - -Des.node.name=Worker1
        - -Des.node.data=true
        - -Des.http.enabled=false
        - -Des.node.master=false
    volumes_from:
        - dataw1
    environment:
        - ES_HEAP_SIZE=2g

dataw1:
    image: busybox
    tty: true
    command:
        - cat
    volumes:
        - /usr/share/elasticsearch/data
    stdin_open: true

esworker2:
    image: eeacms/elastic:1.7.5-1.6
#    build: ./eea.docker.elastic/
    restart: always
    command: # Data, no http, river, can't be master
        - elasticsearch
        - -Des.node.name=Worker2
        - -Des.cluster.name="es_zotya_test"
        - -Des.node.data=true
        - -Des.http.enabled=false
        - -Des.node.master=false
    volumes_from:
        - dataw2
    environment:
        - ES_HEAP_SIZE=2g

dataw2:
    image: busybox
    tty: true
    command:
        - cat
    volumes:
        - /usr/share/elasticsearch/data
    stdin_open: true
