PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#>
PREFIX aq: <http://rdfdata.eionet.europa.eu/airquality/ontology/>
PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>
PREFIX obligations: <http://rod.eionet.europa.eu/obligations/>
PREFIX aqr: <http://reference.eionet.europa.eu/aq/ontology/>

SELECT DISTINCT

md5(concat(?Country, xsd:string(?ReportingYear),?Namespace ,?MeasureId  ,?VersionId , ?CodeOfMeasure, ?Name, ?Description ,?MeasureClassification ,?AdministrativeLevel ,xsd:string(?TimeScale) ,xsd:string(?SpatialScale),?SourceSectors ,xsd:string(?EstimatedImplementationCosts) ,?Currency  ,?CommentOnCosts,?Status,xsd:string(?ImplementationBegin) ,xsd:string(?ImplementationEnd) ,xsd:string(?PlannedFullEffectDate) ,?MonitoringProgressIndicators ,xsd:string(?QuantityOfReducedEmissions),?CommentOnEmissionReductions ,xsd:string(?LevelOfConcentration) ,xsd:string(?NumberOfExceedances) ,xsd:string(?SpecificationOfHours) ,?CommentOnExpectedImpact ,xsd:string(?exceedanceAffectedURI) ,xsd:string(?usedForScenarioURI),?envelope))  as ?_id

?Country as ?CountryOrTerritory  
YEAR(xsd:date(?endOfPeriod)) AS ?ReportingYear 
?Namespace 
?MeasureId 
?VersionId 
?CodeOfMeasure 
?Name 
?Description 
?MeasureClassification 
?MeasureType 
?AdministrativeLevel 
?TimeScale 
?SpatialScale 
?SourceSectors 
?EstimatedImplementationCosts 
?Currency 
?CommentOnCosts 
?Status 
?ImplementationBegin 
?ImplementationEnd 
?PlannedFullEffectDate 
?MonitoringProgressIndicators 
?QuantityOfReducedEmissions 
?CommentOnEmissionReductions 
?LevelOfConcentration 
?NumberOfExceedances 
?SpecificationOfHours 
?CommentOnExpectedImpact 
#?exceedanceAffectedURI as ?SourceApportionmentId1 
replace(replace(replace(str(?exceedanceAffectedURI),"http://reference.eionet.europa.eu/aq/",""),?Namespace ,""),"/","") as ?SourceApportionmentId 
#?usedForScenarioURI as ?ScenariosId1 
#replace(replace(replace(str(?usedForScenarioURI),"http://reference.eionet.europa.eu/aq/",""),?Namespace ,""),"/","") as ?ScenariosId
?MeasureId as ?ScenariosId
?envelope

WHERE {{
  #test
  #VALUES ?envelope { <http://cdr.eionet.europa.eu/at/eu/aqd/k/envwk0gw> }
  #VALUES ?Country { 'Austria' }
  #VALUES ?endOfPeriod { '2016-12-31' }
  #VALUES ?source { <http://cdr.eionet.europa.eu/at/eu/aqd/k/envwk0gw/Measure_AT_0008_20_AQ_MEA_AT_07_M02_2017_02_23_14_00_793.xml> }

  VALUES ?envelope { <<envelope>> }
  VALUES ?Country { 'Country' }
  VALUES ?endOfPeriod { 'endOfPeriod' }
  VALUES ?source { <<source>> }

  GRAPH ?source {
    ?XMLURI a aq:AQD_Measures .
    ?XMLURI aq:inspireId ?inspireURI .
    ?XMLURI aq:code ?CodeOfMeasure .
    ?XMLURI aq:name ?Name .
    ?XMLURI aq:description ?Description .

    ?XMLURI aq:administrativeLevel ?administrativeLevelURI .
    ?XMLURI aq:timeScale ?timeScaleURI .
    ?XMLURI aq:plannedImplementation ?plannedImplementationURI .
    ?XMLURI aq:reductionOfEmissions ?reductionOfEmissionsURI .
  }

  {
    SELECT DISTINCT
      ?MeasureClassification
      ?XMLURI
    WHERE {{
      GRAPH ?source {
       ?XMLURI aq:classification ?classificationURI .
      }
      ?classificationURI rdfs:label ?MeasureClassification .
    }}
  }

  OPTIONAL{?XMLURI aq:measureType ?measureTypeURI .
    ?measureTypeURI rdfs:label ?MeasureType
  }

  ?administrativeLevelURI rdfs:label ?AdministrativeLevel .
  ?timeScaleURI rdfs:label ?TimeScale .

  {
    SELECT DISTINCT
      ?SourceSectors
      ?XMLURI
    WHERE {{
      GRAPH ?source {
        ?XMLURI aq:sourceSectors ?sourceSectorsURI .
      }
        ?sourceSectorsURI rdfs:label ?SourceSectors .
    }}
  }
  
  {
    SELECT DISTINCT
      ?SpatialScale
      ?XMLURI
    WHERE {{
      GRAPH ?source {
        ?XMLURI aq:spatialScale ?spatialScaleURI .
      }
        ?spatialScaleURI rdfs:label ?SpatialScale .
    }}
  }

  OPTIONAL{ ?plannedImplementationURI aq:status ?statusURI .
            ?statusURI rdfs:label ?Status} .

  OPTIONAL{ ?plannedImplementationURI aq:status ?statusURI .
            ?plannedImplementationURI aq:implementationPlannedTimePeriod ?implementationPlannedTimePeriodURI} .

  OPTIONAL{ ?plannedImplementationURI aq:status ?statusURI .
            ?plannedImplementationURI aq:plannedFullEffectDate ?plannedFullEffectDateURI}

  OPTIONAL{ ?plannedImplementationURI aq:status ?statusURI .                          
            ?plannedImplementationURI aq:comment ?CommentOnImplementation} .

  OPTIONAL{ ?plannedImplementationURI aq:status ?statusURI .
            ?plannedImplementationURI aq:monitoringProgressIndicators ?MonitoringProgressIndicators} .

  OPTIONAL{ ?reductionOfEmissionsURI aq:quantity ?QuantityOfReducedEmissions} .
  OPTIONAL{ ?reductionOfEmissionsURI aq:comment ?CommentOnEmissionReductions} .
  
  OPTIONAL{ ?plannedImplementationURI aq:implementationPlannedTimePeriod ?implementationPlannedTimePeriodURI . 
           ?implementationPlannedTimePeriodURI aq:beginPosition ?ImplementationBegin 
  }

  OPTIONAL{ ?plannedImplementationURI aq:implementationPlannedTimePeriod ?implementationPlannedTimePeriodURI . 
           ?implementationPlannedTimePeriodURI aq:endPosition ?ImplementationEnd
  }

  OPTIONAL{ ?plannedImplementationURI aq:plannedFullEffectDate ?plannedFullEffectDateURI .
            ?plannedFullEffectDateURI rdfs:label ?PlannedFullEffectDate
  } 

  OPTIONAL{ ?plannedImplementationURI aq:plannedFullEffectDate ?plannedFullEffectDateURI .
            ?plannedImplementationURI aq:comment ?CommentOnImplementation
  }

  OPTIONAL{ ?XMLURI aq:expectedImpact ?expectedImpactURI .
            ?expectedImpactURI aq:levelOfConcentration ?LevelOfConcentration 
          }

  OPTIONAL{ ?XMLURI aq:expectedImpact ?expectedImpactURI .
            ?expectedImpactURI aq:numberOfExceedances ?NumberOfExceedances 
          }

  OPTIONAL{ ?XMLURI aq:expectedImpact ?expectedImpactURI .
            ?expectedImpactURI aq:levelOfConcentration ?LevelOfConcentration 
          }

  OPTIONAL{ ?XMLURI aq:expectedImpact ?expectedImpactURI .
            ?expectedImpactURI aq:specificationOfHours ?SpecificationOfHours 
          }

  OPTIONAL{ ?XMLURI aq:expectedImpact ?expectedImpactURI .
            ?expectedImpactURI aq:comment ?CommentOnExpectedImpact
          }
  
  OPTIONAL{ ?XMLURI aq:usedForScenario ?usedForScenarioURI .
            ?usedForScenarioURI aqr:hasDeclaration ?scenariosXMLURI .
            ?scenariosXMLURI aq:sourceApportionment ?exceedanceAffectedURI
          }

  #OPTIONAL{ ?XMLURI aq:usedForScenario ?usedForScenarioURI }

  OPTIONAL {
    SELECT DISTINCT
      ?Currency
      ?XMLURI
    WHERE {{
      GRAPH ?source {
        ?XMLURI aq:costs ?costsURI .
      }     
        ?costsURI aq:currency ?currencyURI .
        ?currencyURI rdfs:label ?Currency .
    }}
  }

  OPTIONAL {
    SELECT DISTINCT
      ?estimatedImplementationCosts
      ?XMLURI
    WHERE {{
      GRAPH ?source {
        ?XMLURI aq:costs ?costsURI .
      }
        ?costsURI aq:estimatedImplementationCosts ?estimatedImplementationCosts .
    }}
  }

  ?inspireURI aq:namespace ?Namespace .
  ?inspireURI aq:localId ?MeasureId .
  ?inspireURI aq:versionId ?VersionId .
}}
