PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#>
PREFIX aq: <http://rdfdata.eionet.europa.eu/airquality/ontology/>
PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>
PREFIX obligations: <http://rod.eionet.europa.eu/obligations/>
PREFIX aqr: <http://reference.eionet.europa.eu/aq/ontology/>

SELECT DISTINCT

md5(concat(?Country, xsd:string(?ReportingYear),?Namespace ,?MeasureId  ,?VersionId , ?CodeOfMeasure, ?Name, ?Description ,?MeasureClassification ,?AdministrativeLevel ,xsd:string(?TimeScale) ,xsd:string(?SpatialScale),?SourceSectors ,xsd:string(?EstimatedImplementationCosts) ,?Currency  ,?CommentOnCosts,?Status,xsd:string(?ImplementationBegin) ,xsd:string(?ImplementationEnd) ,xsd:string(?PlannedFullEffectDate) ,?MonitoringProgressIndicators ,xsd:string(?QuantityOfReducedEmissions),?CommentOnEmissionReductions ,xsd:string(?LevelOfConcentration) ,xsd:string(?NumberOfExceedances) ,xsd:string(?SpecificationOfHours) ,?CommentOnExpectedImpact ,xsd:string(?exceedanceAffectedURI) ,xsd:string(?usedForScenarioURI),?envelope))  as ?_id

?Country as ?CountryOrTerritory  
YEAR(xsd:date(?endOfPeriod)) AS ?ReportingYear 
?Namespace 
?MeasureId 
?VersionId 
?CodeOfMeasure 
?Name 
?Description 
?MeasureClassification 
?MeasureType 
?AdministrativeLevel 
?TimeScale 
?SpatialScale 
?SourceSectors 
?EstimatedImplementationCosts 
?Currency 
?CommentOnCosts 
?Status 
?ImplementationBegin 
?ImplementationEnd 
?PlannedFullEffectDate 
?MonitoringProgressIndicators 
?QuantityOfReducedEmissions 
?CommentOnEmissionReductions 
?LevelOfConcentration 
?NumberOfExceedances 
?SpecificationOfHours 
?CommentOnExpectedImpact 
#?exceedanceAffectedURI as ?SourceApportionmentId1 
replace(replace(replace(str(?exceedanceAffectedURI),"http://reference.eionet.europa.eu/aq/",""),?Namespace ,""),"/","") as ?SourceApportionmentId 
#?usedForScenarioURI as ?ScenariosId1 
replace(replace(replace(str(?usedForScenarioURI),"http://reference.eionet.europa.eu/aq/",""),?Namespace ,""),"/","") as ?ScenariosId
?envelope

WHERE {{
  GRAPH ?source {
    ?XMLURI a aq:AQD_Measures .
    ?XMLURI aq:inspireId ?inspireURI .
    ?XMLURI aq:code ?CodeOfMeasure .
    ?XMLURI aq:name ?Name .
    ?XMLURI aq:description ?Description .
    ?XMLURI aq:classification ?classificationURI .
    OPTIONAL{?XMLURI aq:measureType ?measureTypeURI} .
    ?XMLURI aq:administrativeLevel ?administrativeLevelURI .
    ?XMLURI aq:timeScale ?timeScaleURI .
    ?XMLURI aq:spatialScale ?spatialScaleURI .
    ?XMLURI aq:sourceSectors ?sourceSectorsURI .
    ?XMLURI aq:plannedImplementation ?plannedImplementationURI .
    ?XMLURI aq:reductionOfEmissions ?reductionOfEmissionsURI .
  }
  ?source dcterms:isPartOf ?envelope .
  ?envelope rod:released ?released .
  ?envelope rod:locality ?locality .
  ?envelope rod:obligation ?obliURI .
  ?envelope rod:startOfPeriod ?startOfPeriod .
  ?envelope rod:endOfPeriod ?endOfPeriod .

  OPTIONAL {?XMLURI aq:costs ?costsURI} .
  OPTIONAL{?XMLURI aq:expectedImpact ?expectedImpactURI} .
  #OPTIONAL{?XMLURI aq:exceedanceAffected ?exceedanceAffectedURI} .
  OPTIONAL{?XMLURI aq:usedForScenario ?usedForScenarioURI} .
  OPTIONAL{?usedForScenarioURI aqr:hasDeclaration ?scenariosXMLURI} .
  OPTIONAL {?scenariosXMLURI aq:sourceApportionment ?exceedanceAffectedURI} .

  ?classificationURI rdfs:label ?MeasureClassification .
  OPTIONAL{?measureTypeURI rdfs:label ?MeasureType} .
  ?administrativeLevelURI rdfs:label ?AdministrativeLevel .
  ?timeScaleURI rdfs:label ?TimeScale .
  ?spatialScaleURI rdfs:label ?SpatialScale .
  ?sourceSectorsURI rdfs:label ?SourceSectors .

  OPTIONAL{?costsURI aq:comment ?CommentOnCosts} .
  OPTIONAL{?costsURI aq:estimatedImplementationCosts ?estimatedImplementationCosts} .
  OPTIONAL{?costsURI aq:currency ?currencyURI} .
  OPTIONAL{?currencyURI rdfs:label ?Currency} .

  OPTIONAL{?plannedImplementationURI aq:status ?statusURI} .
  OPTIONAL{?plannedImplementationURI aq:implementationPlannedTimePeriod ?implementationPlannedTimePeriodURI} .
  OPTIONAL{?plannedImplementationURI aq:plannedFullEffectDate ?plannedFullEffectDateURI} .
  OPTIONAL{?plannedImplementationURI aq:comment ?CommentOnImplementation} .
  OPTIONAL{?plannedImplementationURI aq:monitoringProgressIndicators ?MonitoringProgressIndicators} .

  OPTIONAL{?statusURI rdfs:label ?Status} .
  OPTIONAL{?plannedFullEffectDateURI rdfs:label ?PlannedFullEffectDate} .
  OPTIONAL{?implementationPlannedTimePeriodURI aq:beginPosition ?ImplementationBegin} .
  OPTIONAL{?implementationPlannedTimePeriodURI aq:endPosition ?ImplementationEnd} .

  OPTIONAL{?reductionOfEmissionsURI aq:quantity ?QuantityOfReducedEmissions} .
  OPTIONAL{?reductionOfEmissionsURI aq:comment ?CommentOnEmissionReductions} .
  #OPTIONAL{?reductionOfEmissionsURI aq:unit ?unitURI} .

  OPTIONAL{?expectedImpactURI aq:levelOfConcentration ?LevelOfConcentration} .
  OPTIONAL{?expectedImpactURI aq:numberOfExceedances ?NumberOfExceedances} .
  OPTIONAL{?expectedImpactURI aq:specificationOfHours ?SpecificationOfHours} .
  OPTIONAL{?expectedImpactURI aq:comment ?CommentOnExpectedImpact} .
 
  ?locality rod:localityName ?Country .
  ?obliURI rdfs:label ?Obligation .

  ?inspireURI aq:namespace ?Namespace .
  ?inspireURI aq:localId ?MeasureId .
  ?inspireURI aq:versionId ?VersionId .

  #FILTER (?envelope = <http://cdr.eionet.europa.eu/bg/eu/aqd/k/envvjk7zg>)
  FILTER (?envelope = <<envelope>>)
}}