PREFIX tableFile: <http://semantic.eea.europa.eu/project/pam/pam2018.csv#>

SELECT 
DISTINCT(?Country)



FROM <http://semantic.eea.europa.eu/project/pam/pam2018.csv>
WHERE {
_:rec tableFile:Country ?Country .

}