PREFIX tableFile: <http://semantic.eea.europa.eu/home/szabozo0/pam2018.csv#>

SELECT 
concat(?Country, "_", ?ID_of_policy_or_measure) as ?_id
?Country
?Report_ID
?Report_ID_ES
?Name_of_policy_or_measure
?Single_policy_or_measure__or_group_of_measures
?ID_of_policy_or_measure
?Policies_or_measures_included_in_the_group
?Type_of_policy_instrument
?Status_of_implementation
?Policy_impacting_EU_ETS__ESD_or_LULUCF_emissions
?Sector_s__affected
?Objective_s__lookup_only4facets
?Objective_s_
?Total_GHG_emissions_reductions_in_2020__kt_CO2eq_y_
?Total_GHG_emissions_reductions_in_2030__kt_CO2eq_y_
?Entities_responsible_for_implementing_the_policy__type_
?Entities_responsible_for_implementing_the_policy
?Implementation_period_start
?Is_the_policy_or_measure_related_to_a_Union_policy_
?Related_Union_Policy
?GHG_s__affected
?Projection_scenario_in_which_the_policy_or_measure_is_included
?Link_to_national_report
?Description
?Quantified_objective
?Implementation_period_finish
?Indicator_used_to_monitor_and_evaluate_progress_over_time
?General_comment
?Main_reference
?GHG_emissions_reductions_EU_ETS_in_2020__kt_CO2eq_y_
?GHG_emissions_reductions_ESD_in_2020__kt_CO2eq_y_
?GHG_emissions_reductions_EU_ETS_in_2025__kt_CO2eq_y_
?GHG_emissions_reductions_ESD_in_2025__kt_CO2eq_y_
?Total_GHG_emissions_reductions_in_2025__kt_CO2eq_y_
?GHG_emissions_reductions_EU_ETS_in_2030__kt_CO2eq_y_
?GHG_emissions_reductions_ESD_in_2030__kt_CO2eq_y_
?GHG_emissions_reductions_EU_ETS_in_2035__kt_CO2eq_y_
?GHG_emissions_reductions_ESD_in_2035__kt_CO2eq_y_
?Total_GHG_emissions_reductions_in_2035__kt_CO2eq_y_
?URL_to_main_reference
?Reference_for_ex_ante_assessment
?Web_link_for_ex_ante_assessment
?Year_for_which_reduction_applies__ex_post_
?Average_ex_post_emission_reduction__kt_CO2eq_y_
?Explanation_of_the_basis_for_the_mitigation_estimates
?Factors_affected_by_the_policy_or_measure
?Reference_for_ex_post_assessment
?Web_link_for_ex_post_assessment
?Projected_costs__EUR_per_tonne_CO2eq_reduced__sequestered_
?Projected_absolute_costs_per_year__EUR_
?Year_projected_cost_has_been_calculated_for
?Price_reference_year__projected_costs_
?Projected_benefits__EUR_per_tonne_CO2eq_reduced__sequestered_
?Projected_absolute_benefit_per_year__EUR_
?Projected_net_costs__EUR_per_tonne_CO2eq_reduced__sequestered_
?Projected_net_cost_per_year__EUR_
?Description_of_projected_cost_estimates
?Reference_for_projected_costs_and_benefits
?Web_link_for_projected_costs_and_benefits
?Realised_costs___EUR_per_tonne_CO2eq_reduced__sequestered_
?Realised_absolute_costs_per_year__EUR_
?Year_realised_cost_has_been_calculated_for
?Price_reference_year__realised_costs_
?Realised_benefits__EUR_per_tonne_CO2eq_reduced__sequestered_
?Realised_absolute_benefit_per_year__EUR_
?Realised_net_costs__EUR_per_tonne_CO2eq_reduced__sequestered_
?Realised_net_cost_per_year__EUR_
?Description_of_realised_cost_estimates
?Reference_for_realised_costs_and_benefits
?Web_link_for_realised_costs_and_benefits
?Status_of_implementation_clean
?Implementation_period_start_clean
?Projection_scenario_in_which_the_policy_or_measure_is_included_clean
?Is_the_policy_or_measure_related_to_a_Union_policy__clean
?Union_policy_lookup_only4facets_clean


FROM <http://semantic.eea.europa.eu/home/szabozo0/pam2018.csv>
WHERE {
_:rec tableFile:Country ?Country .
_:rec tableFile:Report_ID ?Report_ID .
_:rec tableFile:Report_ID_ES ?Report_ID_ES .
_:rec tableFile:Name_of_policy_or_measure ?Name_of_policy_or_measure .
_:rec tableFile:Single_policy_or_measure__or_group_of_measures ?Single_policy_or_measure__or_group_of_measures .
_:rec tableFile:ID_of_policy_or_measure ?ID_of_policy_or_measure .
_:rec tableFile:Policies_or_measures_included_in_the_group ?Policies_or_measures_included_in_the_group .
_:rec tableFile:Type_of_policy_instrument ?Type_of_policy_instrument .
_:rec tableFile:Status_of_implementation ?Status_of_implementation .
_:rec tableFile:Policy_impacting_EU_ETS__ESD_or_LULUCF_emissions ?Policy_impacting_EU_ETS__ESD_or_LULUCF_emissions .
_:rec tableFile:Sector_s__affected ?Sector_s__affected .
_:rec tableFile:Objective_s__lookup_only4facets ?Objective_s__lookup_only4facets .
_:rec tableFile:Objective_s_ ?Objective_s_ .
_:rec tableFile:Total_GHG_emissions_reductions_in_2020__kt_CO2eq_y_ ?Total_GHG_emissions_reductions_in_2020__kt_CO2eq_y_ .
_:rec tableFile:Total_GHG_emissions_reductions_in_2030__kt_CO2eq_y_ ?Total_GHG_emissions_reductions_in_2030__kt_CO2eq_y_ .
_:rec tableFile:Entities_responsible_for_implementing_the_policy__type_ ?Entities_responsible_for_implementing_the_policy__type_ .
_:rec tableFile:Entities_responsible_for_implementing_the_policy ?Entities_responsible_for_implementing_the_policy .
_:rec tableFile:Implementation_period_start ?Implementation_period_start .
_:rec tableFile:Is_the_policy_or_measure_related_to_a_Union_policy_ ?Is_the_policy_or_measure_related_to_a_Union_policy_ .
_:rec tableFile:Union_policies_lookup_only4facets ?Union_policies_lookup_only4facets .
_:rec tableFile:Related_Union_Policy ?Related_Union_Policy .
_:rec tableFile:GHG_s__affected ?GHG_s__affected .
_:rec tableFile:Projection_scenario_in_which_the_policy_or_measure_is_included ?Projection_scenario_in_which_the_policy_or_measure_is_included .
_:rec tableFile:Link_to_national_report ?Link_to_national_report .
_:rec tableFile:Description ?Description .
_:rec tableFile:Quantified_objective ?Quantified_objective .
_:rec tableFile:Implementation_period_finish ?Implementation_period_finish .
_:rec tableFile:Indicator_used_to_monitor_and_evaluate_progress_over_time ?Indicator_used_to_monitor_and_evaluate_progress_over_time .
_:rec tableFile:General_comment ?General_comment .
_:rec tableFile:Main_reference ?Main_reference .
_:rec tableFile:URL_to_main_reference ?URL_to_main_reference .
_:rec tableFile:GHG_emissions_reductions_EU_ETS_in_2020__kt_CO2eq_y_ ?GHG_emissions_reductions_EU_ETS_in_2020__kt_CO2eq_y_ .
_:rec tableFile:GHG_emissions_reductions_ESD_in_2020__kt_CO2eq_y_ ?GHG_emissions_reductions_ESD_in_2020__kt_CO2eq_y_ .
_:rec tableFile:GHG_emissions_reductions_EU_ETS_in_2025__kt_CO2eq_y_ ?GHG_emissions_reductions_EU_ETS_in_2025__kt_CO2eq_y_ .
_:rec tableFile:GHG_emissions_reductions_ESD_in_2025__kt_CO2eq_y_ ?GHG_emissions_reductions_ESD_in_2025__kt_CO2eq_y_ .
_:rec tableFile:Total_GHG_emissions_reductions_in_2025__kt_CO2eq_y_ ?Total_GHG_emissions_reductions_in_2025__kt_CO2eq_y_ .
_:rec tableFile:GHG_emissions_reductions_EU_ETS_in_2030__kt_CO2eq_y_ ?GHG_emissions_reductions_EU_ETS_in_2030__kt_CO2eq_y_ .
_:rec tableFile:GHG_emissions_reductions_ESD_in_2030__kt_CO2eq_y_ ?GHG_emissions_reductions_ESD_in_2030__kt_CO2eq_y_ .
_:rec tableFile:GHG_emissions_reductions_EU_ETS_in_2035__kt_CO2eq_y_ ?GHG_emissions_reductions_EU_ETS_in_2035__kt_CO2eq_y_ .
_:rec tableFile:GHG_emissions_reductions_ESD_in_2035__kt_CO2eq_y_ ?GHG_emissions_reductions_ESD_in_2035__kt_CO2eq_y_ .
_:rec tableFile:Total_GHG_emissions_reductions_in_2035__kt_CO2eq_y_ ?Total_GHG_emissions_reductions_in_2035__kt_CO2eq_y_ .
_:rec tableFile:Reference_for_ex_ante_assessment ?Reference_for_ex_ante_assessment .
_:rec tableFile:Web_link_for_ex_ante_assessment ?Web_link_for_ex_ante_assessment .
_:rec tableFile:Year_for_which_reduction_applies__ex_post_ ?Year_for_which_reduction_applies__ex_post_ .
_:rec tableFile:Average_ex_post_emission_reduction__kt_CO2eq_y_ ?Average_ex_post_emission_reduction__kt_CO2eq_y_ .
_:rec tableFile:Explanation_of_the_basis_for_the_mitigation_estimates ?Explanation_of_the_basis_for_the_mitigation_estimates .
_:rec tableFile:Factors_affected_by_the_policy_or_measure ?Factors_affected_by_the_policy_or_measure .
_:rec tableFile:Reference_for_ex_post_assessment ?Reference_for_ex_post_assessment .
_:rec tableFile:Web_link_for_ex_post_assessment ?Web_link_for_ex_post_assessment .
_:rec tableFile:Projected_costs__EUR_per_tonne_CO2eq_reduced__sequestered_ ?Projected_costs__EUR_per_tonne_CO2eq_reduced__sequestered_ .
_:rec tableFile:Projected_absolute_costs_per_year__EUR_ ?Projected_absolute_costs_per_year__EUR_ .
_:rec tableFile:Year_projected_cost_has_been_calculated_for ?Year_projected_cost_has_been_calculated_for .
_:rec tableFile:Price_reference_year__projected_costs_ ?Price_reference_year__projected_costs_ .
_:rec tableFile:Projected_benefits__EUR_per_tonne_CO2eq_reduced__sequestered_ ?Projected_benefits__EUR_per_tonne_CO2eq_reduced__sequestered_ .
_:rec tableFile:Projected_absolute_benefit_per_year__EUR_ ?Projected_absolute_benefit_per_year__EUR_ .
_:rec tableFile:Projected_net_costs__EUR_per_tonne_CO2eq_reduced__sequestered_ ?Projected_net_costs__EUR_per_tonne_CO2eq_reduced__sequestered_ .
_:rec tableFile:Projected_net_cost_per_year__EUR_ ?Projected_net_cost_per_year__EUR_ .
_:rec tableFile:Description_of_projected_cost_estimates ?Description_of_projected_cost_estimates .
_:rec tableFile:Reference_for_projected_costs_and_benefits ?Reference_for_projected_costs_and_benefits .
_:rec tableFile:Web_link_for_projected_costs_and_benefits ?Web_link_for_projected_costs_and_benefits .
_:rec tableFile:Realised_costs___EUR_per_tonne_CO2eq_reduced__sequestered_ ?Realised_costs___EUR_per_tonne_CO2eq_reduced__sequestered_ .
_:rec tableFile:Realised_absolute_costs_per_year__EUR_ ?Realised_absolute_costs_per_year__EUR_ .
_:rec tableFile:Year_realised_cost_has_been_calculated_for ?Year_realised_cost_has_been_calculated_for .
_:rec tableFile:Price_reference_year__realised_costs_ ?Price_reference_year__realised_costs_ .
_:rec tableFile:Realised_benefits__EUR_per_tonne_CO2eq_reduced__sequestered_ ?Realised_benefits__EUR_per_tonne_CO2eq_reduced__sequestered_ .
_:rec tableFile:Realised_absolute_benefit_per_year__EUR_ ?Realised_absolute_benefit_per_year__EUR_ .
_:rec tableFile:Realised_net_costs__EUR_per_tonne_CO2eq_reduced__sequestered_ ?Realised_net_costs__EUR_per_tonne_CO2eq_reduced__sequestered_ .
_:rec tableFile:Realised_net_cost_per_year__EUR_ ?Realised_net_cost_per_year__EUR_ .
_:rec tableFile:Description_of_realised_cost_estimates ?Description_of_realised_cost_estimates .
_:rec tableFile:Reference_for_realised_costs_and_benefits ?Reference_for_realised_costs_and_benefits .
_:rec tableFile:Web_link_for_realised_costs_and_benefits ?Web_link_for_realised_costs_and_benefits .
_:rec tableFile:Status_of_implementation_clean ?Status_of_implementation_clean .
_:rec tableFile:Implementation_period_start_clean ?Implementation_period_start_clean .
_:rec tableFile:Projection_scenario_in_which_the_policy_or_measure_is_included_clean ?Projection_scenario_in_which_the_policy_or_measure_is_included_clean .
_:rec tableFile:Is_the_policy_or_measure_related_to_a_Union_policy__clean ?Is_the_policy_or_measure_related_to_a_Union_policy__clean .
_:rec tableFile:Union_policy_lookup_only4facets_clean ?Union_policy_lookup_only4facets_clean .
FILTER (?Country = '<Country>')
}
