PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>
PREFIX obligation: <http://rod.eionet.europa.eu/obligations/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT
?source
?envelope
?released
?startOfPeriod
?CountryOrTerritory
WHERE {{
  SELECT DISTINCT
    ?CountryOrTerritory
    max(?released) as ?released
    ?startOfPeriod
  WHERE {
    ?envelope rod:released ?released .
    ?envelope rod:startOfPeriod ?startOfPeriod .
    ?envelope rod:obligation obligation:672 .
    ?envelope rod:locality ?locality .
    ?locality rod:localityName ?CountryOrTerritory .
  } GROUP BY ?CountryOrTerritory ?startOfPeriod
}
?envelope rod:released ?released .
?envelope rdf:type rod:Delivery .
?source dcterms:isPartOf ?envelope .
?source a rod:File .

}
ORDER BY ?CountryOrTerritory
